variable "project_names" {}
variable "cidr_block_snet_appprod" {}
variable "cidr_block_snet_dbprod" {}
variable "cidr_block_snet_mgmt" {}
variable "cidr_block_snet_appdev" {}
variable "cidr_block_snet_appuat" {}
variable "cmc_sg_mgmt_basion" {}
variable "cmc_sg_app_prod" {}
variable "cmc_sg_db_prod" {}
variable "cmc_sg_dev" {}
variable "cmc_sg_uat" {}
variable "cmc_instance_type" {}
variable "ami" {}
