variable "igw" {}
variable "vpc_ids" {}
variable "cidr_block_snet_mgmt" {}
variable "cidr_block_snet_appdev" {}
variable "cidr_block_snet_dbdev" {}
variable "cidr_block_snet_appuat" {}
variable "cidr_block_snet_dbuat" {}
variable "cidr_block_snet_appprod" {}
variable "cidr_block_snet_dbprod" {}
variable "cidr_block_public_snet_fw" {}